// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: repo-command-parameter.proto

#ifndef PROTOBUF_repo_2dcommand_2dparameter_2eproto__INCLUDED
#define PROTOBUF_repo_2dcommand_2dparameter_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace ndn_message {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_repo_2dcommand_2dparameter_2eproto();
void protobuf_AssignDesc_repo_2dcommand_2dparameter_2eproto();
void protobuf_ShutdownFile_repo_2dcommand_2dparameter_2eproto();

class RepoCommandParameterMessage;
class RepoCommandParameterMessage_Name;
class RepoCommandParameterMessage_Selectors;
class RepoCommandParameterMessage_RepoCommandParameter;

// ===================================================================

class RepoCommandParameterMessage_Name : public ::google::protobuf::Message {
 public:
  RepoCommandParameterMessage_Name();
  virtual ~RepoCommandParameterMessage_Name();

  RepoCommandParameterMessage_Name(const RepoCommandParameterMessage_Name& from);

  inline RepoCommandParameterMessage_Name& operator=(const RepoCommandParameterMessage_Name& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RepoCommandParameterMessage_Name& default_instance();

  void Swap(RepoCommandParameterMessage_Name* other);

  // implements Message ----------------------------------------------

  RepoCommandParameterMessage_Name* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RepoCommandParameterMessage_Name& from);
  void MergeFrom(const RepoCommandParameterMessage_Name& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated bytes component = 8;
  inline int component_size() const;
  inline void clear_component();
  static const int kComponentFieldNumber = 8;
  inline const ::std::string& component(int index) const;
  inline ::std::string* mutable_component(int index);
  inline void set_component(int index, const ::std::string& value);
  inline void set_component(int index, const char* value);
  inline void set_component(int index, const void* value, size_t size);
  inline ::std::string* add_component();
  inline void add_component(const ::std::string& value);
  inline void add_component(const char* value);
  inline void add_component(const void* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& component() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_component();

  // @@protoc_insertion_point(class_scope:ndn_message.RepoCommandParameterMessage.Name)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::std::string> component_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_repo_2dcommand_2dparameter_2eproto();
  friend void protobuf_AssignDesc_repo_2dcommand_2dparameter_2eproto();
  friend void protobuf_ShutdownFile_repo_2dcommand_2dparameter_2eproto();

  void InitAsDefaultInstance();
  static RepoCommandParameterMessage_Name* default_instance_;
};
// -------------------------------------------------------------------

class RepoCommandParameterMessage_Selectors : public ::google::protobuf::Message {
 public:
  RepoCommandParameterMessage_Selectors();
  virtual ~RepoCommandParameterMessage_Selectors();

  RepoCommandParameterMessage_Selectors(const RepoCommandParameterMessage_Selectors& from);

  inline RepoCommandParameterMessage_Selectors& operator=(const RepoCommandParameterMessage_Selectors& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RepoCommandParameterMessage_Selectors& default_instance();

  void Swap(RepoCommandParameterMessage_Selectors* other);

  // implements Message ----------------------------------------------

  RepoCommandParameterMessage_Selectors* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RepoCommandParameterMessage_Selectors& from);
  void MergeFrom(const RepoCommandParameterMessage_Selectors& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 min_suffix_components = 13;
  inline bool has_min_suffix_components() const;
  inline void clear_min_suffix_components();
  static const int kMinSuffixComponentsFieldNumber = 13;
  inline ::google::protobuf::uint32 min_suffix_components() const;
  inline void set_min_suffix_components(::google::protobuf::uint32 value);

  // optional uint32 max_suffix_components = 14;
  inline bool has_max_suffix_components() const;
  inline void clear_max_suffix_components();
  static const int kMaxSuffixComponentsFieldNumber = 14;
  inline ::google::protobuf::uint32 max_suffix_components() const;
  inline void set_max_suffix_components(::google::protobuf::uint32 value);

  // optional bytes publisher_public_key_locator = 15;
  inline bool has_publisher_public_key_locator() const;
  inline void clear_publisher_public_key_locator();
  static const int kPublisherPublicKeyLocatorFieldNumber = 15;
  inline const ::std::string& publisher_public_key_locator() const;
  inline void set_publisher_public_key_locator(const ::std::string& value);
  inline void set_publisher_public_key_locator(const char* value);
  inline void set_publisher_public_key_locator(const void* value, size_t size);
  inline ::std::string* mutable_publisher_public_key_locator();
  inline ::std::string* release_publisher_public_key_locator();
  inline void set_allocated_publisher_public_key_locator(::std::string* publisher_public_key_locator);

  // optional uint32 child_selector = 17;
  inline bool has_child_selector() const;
  inline void clear_child_selector();
  static const int kChildSelectorFieldNumber = 17;
  inline ::google::protobuf::uint32 child_selector() const;
  inline void set_child_selector(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:ndn_message.RepoCommandParameterMessage.Selectors)
 private:
  inline void set_has_min_suffix_components();
  inline void clear_has_min_suffix_components();
  inline void set_has_max_suffix_components();
  inline void clear_has_max_suffix_components();
  inline void set_has_publisher_public_key_locator();
  inline void clear_has_publisher_public_key_locator();
  inline void set_has_child_selector();
  inline void clear_has_child_selector();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 min_suffix_components_;
  ::google::protobuf::uint32 max_suffix_components_;
  ::std::string* publisher_public_key_locator_;
  ::google::protobuf::uint32 child_selector_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_repo_2dcommand_2dparameter_2eproto();
  friend void protobuf_AssignDesc_repo_2dcommand_2dparameter_2eproto();
  friend void protobuf_ShutdownFile_repo_2dcommand_2dparameter_2eproto();

  void InitAsDefaultInstance();
  static RepoCommandParameterMessage_Selectors* default_instance_;
};
// -------------------------------------------------------------------

class RepoCommandParameterMessage_RepoCommandParameter : public ::google::protobuf::Message {
 public:
  RepoCommandParameterMessage_RepoCommandParameter();
  virtual ~RepoCommandParameterMessage_RepoCommandParameter();

  RepoCommandParameterMessage_RepoCommandParameter(const RepoCommandParameterMessage_RepoCommandParameter& from);

  inline RepoCommandParameterMessage_RepoCommandParameter& operator=(const RepoCommandParameterMessage_RepoCommandParameter& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RepoCommandParameterMessage_RepoCommandParameter& default_instance();

  void Swap(RepoCommandParameterMessage_RepoCommandParameter* other);

  // implements Message ----------------------------------------------

  RepoCommandParameterMessage_RepoCommandParameter* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RepoCommandParameterMessage_RepoCommandParameter& from);
  void MergeFrom(const RepoCommandParameterMessage_RepoCommandParameter& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .ndn_message.RepoCommandParameterMessage.Name name = 7;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 7;
  inline const ::ndn_message::RepoCommandParameterMessage_Name& name() const;
  inline ::ndn_message::RepoCommandParameterMessage_Name* mutable_name();
  inline ::ndn_message::RepoCommandParameterMessage_Name* release_name();
  inline void set_allocated_name(::ndn_message::RepoCommandParameterMessage_Name* name);

  // optional .ndn_message.RepoCommandParameterMessage.Selectors selectors = 9;
  inline bool has_selectors() const;
  inline void clear_selectors();
  static const int kSelectorsFieldNumber = 9;
  inline const ::ndn_message::RepoCommandParameterMessage_Selectors& selectors() const;
  inline ::ndn_message::RepoCommandParameterMessage_Selectors* mutable_selectors();
  inline ::ndn_message::RepoCommandParameterMessage_Selectors* release_selectors();
  inline void set_allocated_selectors(::ndn_message::RepoCommandParameterMessage_Selectors* selectors);

  // optional uint64 start_block_id = 204;
  inline bool has_start_block_id() const;
  inline void clear_start_block_id();
  static const int kStartBlockIdFieldNumber = 204;
  inline ::google::protobuf::uint64 start_block_id() const;
  inline void set_start_block_id(::google::protobuf::uint64 value);

  // optional uint64 end_block_id = 205;
  inline bool has_end_block_id() const;
  inline void clear_end_block_id();
  static const int kEndBlockIdFieldNumber = 205;
  inline ::google::protobuf::uint64 end_block_id() const;
  inline void set_end_block_id(::google::protobuf::uint64 value);

  // optional uint64 process_id = 206;
  inline bool has_process_id() const;
  inline void clear_process_id();
  static const int kProcessIdFieldNumber = 206;
  inline ::google::protobuf::uint64 process_id() const;
  inline void set_process_id(::google::protobuf::uint64 value);

  // optional uint64 max_interest_num = 211;
  inline bool has_max_interest_num() const;
  inline void clear_max_interest_num();
  static const int kMaxInterestNumFieldNumber = 211;
  inline ::google::protobuf::uint64 max_interest_num() const;
  inline void set_max_interest_num(::google::protobuf::uint64 value);

  // optional uint64 watch_timeout = 212;
  inline bool has_watch_timeout() const;
  inline void clear_watch_timeout();
  static const int kWatchTimeoutFieldNumber = 212;
  inline ::google::protobuf::uint64 watch_timeout() const;
  inline void set_watch_timeout(::google::protobuf::uint64 value);

  // optional uint64 watch_status = 213;
  inline bool has_watch_status() const;
  inline void clear_watch_status();
  static const int kWatchStatusFieldNumber = 213;
  inline ::google::protobuf::uint64 watch_status() const;
  inline void set_watch_status(::google::protobuf::uint64 value);

  // optional uint64 interest_lifetime = 214;
  inline bool has_interest_lifetime() const;
  inline void clear_interest_lifetime();
  static const int kInterestLifetimeFieldNumber = 214;
  inline ::google::protobuf::uint64 interest_lifetime() const;
  inline void set_interest_lifetime(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:ndn_message.RepoCommandParameterMessage.RepoCommandParameter)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_selectors();
  inline void clear_has_selectors();
  inline void set_has_start_block_id();
  inline void clear_has_start_block_id();
  inline void set_has_end_block_id();
  inline void clear_has_end_block_id();
  inline void set_has_process_id();
  inline void clear_has_process_id();
  inline void set_has_max_interest_num();
  inline void clear_has_max_interest_num();
  inline void set_has_watch_timeout();
  inline void clear_has_watch_timeout();
  inline void set_has_watch_status();
  inline void clear_has_watch_status();
  inline void set_has_interest_lifetime();
  inline void clear_has_interest_lifetime();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::ndn_message::RepoCommandParameterMessage_Name* name_;
  ::ndn_message::RepoCommandParameterMessage_Selectors* selectors_;
  ::google::protobuf::uint64 start_block_id_;
  ::google::protobuf::uint64 end_block_id_;
  ::google::protobuf::uint64 process_id_;
  ::google::protobuf::uint64 max_interest_num_;
  ::google::protobuf::uint64 watch_timeout_;
  ::google::protobuf::uint64 watch_status_;
  ::google::protobuf::uint64 interest_lifetime_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(9 + 31) / 32];

  friend void  protobuf_AddDesc_repo_2dcommand_2dparameter_2eproto();
  friend void protobuf_AssignDesc_repo_2dcommand_2dparameter_2eproto();
  friend void protobuf_ShutdownFile_repo_2dcommand_2dparameter_2eproto();

  void InitAsDefaultInstance();
  static RepoCommandParameterMessage_RepoCommandParameter* default_instance_;
};
// -------------------------------------------------------------------

class RepoCommandParameterMessage : public ::google::protobuf::Message {
 public:
  RepoCommandParameterMessage();
  virtual ~RepoCommandParameterMessage();

  RepoCommandParameterMessage(const RepoCommandParameterMessage& from);

  inline RepoCommandParameterMessage& operator=(const RepoCommandParameterMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RepoCommandParameterMessage& default_instance();

  void Swap(RepoCommandParameterMessage* other);

  // implements Message ----------------------------------------------

  RepoCommandParameterMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RepoCommandParameterMessage& from);
  void MergeFrom(const RepoCommandParameterMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef RepoCommandParameterMessage_Name Name;
  typedef RepoCommandParameterMessage_Selectors Selectors;
  typedef RepoCommandParameterMessage_RepoCommandParameter RepoCommandParameter;

  // accessors -------------------------------------------------------

  // required .ndn_message.RepoCommandParameterMessage.RepoCommandParameter repo_command_parameter = 201;
  inline bool has_repo_command_parameter() const;
  inline void clear_repo_command_parameter();
  static const int kRepoCommandParameterFieldNumber = 201;
  inline const ::ndn_message::RepoCommandParameterMessage_RepoCommandParameter& repo_command_parameter() const;
  inline ::ndn_message::RepoCommandParameterMessage_RepoCommandParameter* mutable_repo_command_parameter();
  inline ::ndn_message::RepoCommandParameterMessage_RepoCommandParameter* release_repo_command_parameter();
  inline void set_allocated_repo_command_parameter(::ndn_message::RepoCommandParameterMessage_RepoCommandParameter* repo_command_parameter);

  // @@protoc_insertion_point(class_scope:ndn_message.RepoCommandParameterMessage)
 private:
  inline void set_has_repo_command_parameter();
  inline void clear_has_repo_command_parameter();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::ndn_message::RepoCommandParameterMessage_RepoCommandParameter* repo_command_parameter_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_repo_2dcommand_2dparameter_2eproto();
  friend void protobuf_AssignDesc_repo_2dcommand_2dparameter_2eproto();
  friend void protobuf_ShutdownFile_repo_2dcommand_2dparameter_2eproto();

  void InitAsDefaultInstance();
  static RepoCommandParameterMessage* default_instance_;
};
// ===================================================================


// ===================================================================

// RepoCommandParameterMessage_Name

// repeated bytes component = 8;
inline int RepoCommandParameterMessage_Name::component_size() const {
  return component_.size();
}
inline void RepoCommandParameterMessage_Name::clear_component() {
  component_.Clear();
}
inline const ::std::string& RepoCommandParameterMessage_Name::component(int index) const {
  return component_.Get(index);
}
inline ::std::string* RepoCommandParameterMessage_Name::mutable_component(int index) {
  return component_.Mutable(index);
}
inline void RepoCommandParameterMessage_Name::set_component(int index, const ::std::string& value) {
  component_.Mutable(index)->assign(value);
}
inline void RepoCommandParameterMessage_Name::set_component(int index, const char* value) {
  component_.Mutable(index)->assign(value);
}
inline void RepoCommandParameterMessage_Name::set_component(int index, const void* value, size_t size) {
  component_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RepoCommandParameterMessage_Name::add_component() {
  return component_.Add();
}
inline void RepoCommandParameterMessage_Name::add_component(const ::std::string& value) {
  component_.Add()->assign(value);
}
inline void RepoCommandParameterMessage_Name::add_component(const char* value) {
  component_.Add()->assign(value);
}
inline void RepoCommandParameterMessage_Name::add_component(const void* value, size_t size) {
  component_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
RepoCommandParameterMessage_Name::component() const {
  return component_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
RepoCommandParameterMessage_Name::mutable_component() {
  return &component_;
}

// -------------------------------------------------------------------

// RepoCommandParameterMessage_Selectors

// optional uint32 min_suffix_components = 13;
inline bool RepoCommandParameterMessage_Selectors::has_min_suffix_components() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RepoCommandParameterMessage_Selectors::set_has_min_suffix_components() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RepoCommandParameterMessage_Selectors::clear_has_min_suffix_components() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RepoCommandParameterMessage_Selectors::clear_min_suffix_components() {
  min_suffix_components_ = 0u;
  clear_has_min_suffix_components();
}
inline ::google::protobuf::uint32 RepoCommandParameterMessage_Selectors::min_suffix_components() const {
  return min_suffix_components_;
}
inline void RepoCommandParameterMessage_Selectors::set_min_suffix_components(::google::protobuf::uint32 value) {
  set_has_min_suffix_components();
  min_suffix_components_ = value;
}

// optional uint32 max_suffix_components = 14;
inline bool RepoCommandParameterMessage_Selectors::has_max_suffix_components() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RepoCommandParameterMessage_Selectors::set_has_max_suffix_components() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RepoCommandParameterMessage_Selectors::clear_has_max_suffix_components() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RepoCommandParameterMessage_Selectors::clear_max_suffix_components() {
  max_suffix_components_ = 0u;
  clear_has_max_suffix_components();
}
inline ::google::protobuf::uint32 RepoCommandParameterMessage_Selectors::max_suffix_components() const {
  return max_suffix_components_;
}
inline void RepoCommandParameterMessage_Selectors::set_max_suffix_components(::google::protobuf::uint32 value) {
  set_has_max_suffix_components();
  max_suffix_components_ = value;
}

// optional bytes publisher_public_key_locator = 15;
inline bool RepoCommandParameterMessage_Selectors::has_publisher_public_key_locator() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RepoCommandParameterMessage_Selectors::set_has_publisher_public_key_locator() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RepoCommandParameterMessage_Selectors::clear_has_publisher_public_key_locator() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RepoCommandParameterMessage_Selectors::clear_publisher_public_key_locator() {
  if (publisher_public_key_locator_ != &::google::protobuf::internal::kEmptyString) {
    publisher_public_key_locator_->clear();
  }
  clear_has_publisher_public_key_locator();
}
inline const ::std::string& RepoCommandParameterMessage_Selectors::publisher_public_key_locator() const {
  return *publisher_public_key_locator_;
}
inline void RepoCommandParameterMessage_Selectors::set_publisher_public_key_locator(const ::std::string& value) {
  set_has_publisher_public_key_locator();
  if (publisher_public_key_locator_ == &::google::protobuf::internal::kEmptyString) {
    publisher_public_key_locator_ = new ::std::string;
  }
  publisher_public_key_locator_->assign(value);
}
inline void RepoCommandParameterMessage_Selectors::set_publisher_public_key_locator(const char* value) {
  set_has_publisher_public_key_locator();
  if (publisher_public_key_locator_ == &::google::protobuf::internal::kEmptyString) {
    publisher_public_key_locator_ = new ::std::string;
  }
  publisher_public_key_locator_->assign(value);
}
inline void RepoCommandParameterMessage_Selectors::set_publisher_public_key_locator(const void* value, size_t size) {
  set_has_publisher_public_key_locator();
  if (publisher_public_key_locator_ == &::google::protobuf::internal::kEmptyString) {
    publisher_public_key_locator_ = new ::std::string;
  }
  publisher_public_key_locator_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RepoCommandParameterMessage_Selectors::mutable_publisher_public_key_locator() {
  set_has_publisher_public_key_locator();
  if (publisher_public_key_locator_ == &::google::protobuf::internal::kEmptyString) {
    publisher_public_key_locator_ = new ::std::string;
  }
  return publisher_public_key_locator_;
}
inline ::std::string* RepoCommandParameterMessage_Selectors::release_publisher_public_key_locator() {
  clear_has_publisher_public_key_locator();
  if (publisher_public_key_locator_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = publisher_public_key_locator_;
    publisher_public_key_locator_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void RepoCommandParameterMessage_Selectors::set_allocated_publisher_public_key_locator(::std::string* publisher_public_key_locator) {
  if (publisher_public_key_locator_ != &::google::protobuf::internal::kEmptyString) {
    delete publisher_public_key_locator_;
  }
  if (publisher_public_key_locator) {
    set_has_publisher_public_key_locator();
    publisher_public_key_locator_ = publisher_public_key_locator;
  } else {
    clear_has_publisher_public_key_locator();
    publisher_public_key_locator_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional uint32 child_selector = 17;
inline bool RepoCommandParameterMessage_Selectors::has_child_selector() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RepoCommandParameterMessage_Selectors::set_has_child_selector() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RepoCommandParameterMessage_Selectors::clear_has_child_selector() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RepoCommandParameterMessage_Selectors::clear_child_selector() {
  child_selector_ = 0u;
  clear_has_child_selector();
}
inline ::google::protobuf::uint32 RepoCommandParameterMessage_Selectors::child_selector() const {
  return child_selector_;
}
inline void RepoCommandParameterMessage_Selectors::set_child_selector(::google::protobuf::uint32 value) {
  set_has_child_selector();
  child_selector_ = value;
}

// -------------------------------------------------------------------

// RepoCommandParameterMessage_RepoCommandParameter

// optional .ndn_message.RepoCommandParameterMessage.Name name = 7;
inline bool RepoCommandParameterMessage_RepoCommandParameter::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::clear_name() {
  if (name_ != NULL) name_->::ndn_message::RepoCommandParameterMessage_Name::Clear();
  clear_has_name();
}
inline const ::ndn_message::RepoCommandParameterMessage_Name& RepoCommandParameterMessage_RepoCommandParameter::name() const {
  return name_ != NULL ? *name_ : *default_instance_->name_;
}
inline ::ndn_message::RepoCommandParameterMessage_Name* RepoCommandParameterMessage_RepoCommandParameter::mutable_name() {
  set_has_name();
  if (name_ == NULL) name_ = new ::ndn_message::RepoCommandParameterMessage_Name;
  return name_;
}
inline ::ndn_message::RepoCommandParameterMessage_Name* RepoCommandParameterMessage_RepoCommandParameter::release_name() {
  clear_has_name();
  ::ndn_message::RepoCommandParameterMessage_Name* temp = name_;
  name_ = NULL;
  return temp;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::set_allocated_name(::ndn_message::RepoCommandParameterMessage_Name* name) {
  delete name_;
  name_ = name;
  if (name) {
    set_has_name();
  } else {
    clear_has_name();
  }
}

// optional .ndn_message.RepoCommandParameterMessage.Selectors selectors = 9;
inline bool RepoCommandParameterMessage_RepoCommandParameter::has_selectors() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::set_has_selectors() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::clear_has_selectors() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::clear_selectors() {
  if (selectors_ != NULL) selectors_->::ndn_message::RepoCommandParameterMessage_Selectors::Clear();
  clear_has_selectors();
}
inline const ::ndn_message::RepoCommandParameterMessage_Selectors& RepoCommandParameterMessage_RepoCommandParameter::selectors() const {
  return selectors_ != NULL ? *selectors_ : *default_instance_->selectors_;
}
inline ::ndn_message::RepoCommandParameterMessage_Selectors* RepoCommandParameterMessage_RepoCommandParameter::mutable_selectors() {
  set_has_selectors();
  if (selectors_ == NULL) selectors_ = new ::ndn_message::RepoCommandParameterMessage_Selectors;
  return selectors_;
}
inline ::ndn_message::RepoCommandParameterMessage_Selectors* RepoCommandParameterMessage_RepoCommandParameter::release_selectors() {
  clear_has_selectors();
  ::ndn_message::RepoCommandParameterMessage_Selectors* temp = selectors_;
  selectors_ = NULL;
  return temp;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::set_allocated_selectors(::ndn_message::RepoCommandParameterMessage_Selectors* selectors) {
  delete selectors_;
  selectors_ = selectors;
  if (selectors) {
    set_has_selectors();
  } else {
    clear_has_selectors();
  }
}

// optional uint64 start_block_id = 204;
inline bool RepoCommandParameterMessage_RepoCommandParameter::has_start_block_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::set_has_start_block_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::clear_has_start_block_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::clear_start_block_id() {
  start_block_id_ = GOOGLE_ULONGLONG(0);
  clear_has_start_block_id();
}
inline ::google::protobuf::uint64 RepoCommandParameterMessage_RepoCommandParameter::start_block_id() const {
  return start_block_id_;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::set_start_block_id(::google::protobuf::uint64 value) {
  set_has_start_block_id();
  start_block_id_ = value;
}

// optional uint64 end_block_id = 205;
inline bool RepoCommandParameterMessage_RepoCommandParameter::has_end_block_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::set_has_end_block_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::clear_has_end_block_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::clear_end_block_id() {
  end_block_id_ = GOOGLE_ULONGLONG(0);
  clear_has_end_block_id();
}
inline ::google::protobuf::uint64 RepoCommandParameterMessage_RepoCommandParameter::end_block_id() const {
  return end_block_id_;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::set_end_block_id(::google::protobuf::uint64 value) {
  set_has_end_block_id();
  end_block_id_ = value;
}

// optional uint64 process_id = 206;
inline bool RepoCommandParameterMessage_RepoCommandParameter::has_process_id() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::set_has_process_id() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::clear_has_process_id() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::clear_process_id() {
  process_id_ = GOOGLE_ULONGLONG(0);
  clear_has_process_id();
}
inline ::google::protobuf::uint64 RepoCommandParameterMessage_RepoCommandParameter::process_id() const {
  return process_id_;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::set_process_id(::google::protobuf::uint64 value) {
  set_has_process_id();
  process_id_ = value;
}

// optional uint64 max_interest_num = 211;
inline bool RepoCommandParameterMessage_RepoCommandParameter::has_max_interest_num() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::set_has_max_interest_num() {
  _has_bits_[0] |= 0x00000020u;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::clear_has_max_interest_num() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::clear_max_interest_num() {
  max_interest_num_ = GOOGLE_ULONGLONG(0);
  clear_has_max_interest_num();
}
inline ::google::protobuf::uint64 RepoCommandParameterMessage_RepoCommandParameter::max_interest_num() const {
  return max_interest_num_;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::set_max_interest_num(::google::protobuf::uint64 value) {
  set_has_max_interest_num();
  max_interest_num_ = value;
}

// optional uint64 watch_timeout = 212;
inline bool RepoCommandParameterMessage_RepoCommandParameter::has_watch_timeout() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::set_has_watch_timeout() {
  _has_bits_[0] |= 0x00000040u;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::clear_has_watch_timeout() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::clear_watch_timeout() {
  watch_timeout_ = GOOGLE_ULONGLONG(0);
  clear_has_watch_timeout();
}
inline ::google::protobuf::uint64 RepoCommandParameterMessage_RepoCommandParameter::watch_timeout() const {
  return watch_timeout_;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::set_watch_timeout(::google::protobuf::uint64 value) {
  set_has_watch_timeout();
  watch_timeout_ = value;
}

// optional uint64 watch_status = 213;
inline bool RepoCommandParameterMessage_RepoCommandParameter::has_watch_status() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::set_has_watch_status() {
  _has_bits_[0] |= 0x00000080u;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::clear_has_watch_status() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::clear_watch_status() {
  watch_status_ = GOOGLE_ULONGLONG(0);
  clear_has_watch_status();
}
inline ::google::protobuf::uint64 RepoCommandParameterMessage_RepoCommandParameter::watch_status() const {
  return watch_status_;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::set_watch_status(::google::protobuf::uint64 value) {
  set_has_watch_status();
  watch_status_ = value;
}

// optional uint64 interest_lifetime = 214;
inline bool RepoCommandParameterMessage_RepoCommandParameter::has_interest_lifetime() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::set_has_interest_lifetime() {
  _has_bits_[0] |= 0x00000100u;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::clear_has_interest_lifetime() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::clear_interest_lifetime() {
  interest_lifetime_ = GOOGLE_ULONGLONG(0);
  clear_has_interest_lifetime();
}
inline ::google::protobuf::uint64 RepoCommandParameterMessage_RepoCommandParameter::interest_lifetime() const {
  return interest_lifetime_;
}
inline void RepoCommandParameterMessage_RepoCommandParameter::set_interest_lifetime(::google::protobuf::uint64 value) {
  set_has_interest_lifetime();
  interest_lifetime_ = value;
}

// -------------------------------------------------------------------

// RepoCommandParameterMessage

// required .ndn_message.RepoCommandParameterMessage.RepoCommandParameter repo_command_parameter = 201;
inline bool RepoCommandParameterMessage::has_repo_command_parameter() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RepoCommandParameterMessage::set_has_repo_command_parameter() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RepoCommandParameterMessage::clear_has_repo_command_parameter() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RepoCommandParameterMessage::clear_repo_command_parameter() {
  if (repo_command_parameter_ != NULL) repo_command_parameter_->::ndn_message::RepoCommandParameterMessage_RepoCommandParameter::Clear();
  clear_has_repo_command_parameter();
}
inline const ::ndn_message::RepoCommandParameterMessage_RepoCommandParameter& RepoCommandParameterMessage::repo_command_parameter() const {
  return repo_command_parameter_ != NULL ? *repo_command_parameter_ : *default_instance_->repo_command_parameter_;
}
inline ::ndn_message::RepoCommandParameterMessage_RepoCommandParameter* RepoCommandParameterMessage::mutable_repo_command_parameter() {
  set_has_repo_command_parameter();
  if (repo_command_parameter_ == NULL) repo_command_parameter_ = new ::ndn_message::RepoCommandParameterMessage_RepoCommandParameter;
  return repo_command_parameter_;
}
inline ::ndn_message::RepoCommandParameterMessage_RepoCommandParameter* RepoCommandParameterMessage::release_repo_command_parameter() {
  clear_has_repo_command_parameter();
  ::ndn_message::RepoCommandParameterMessage_RepoCommandParameter* temp = repo_command_parameter_;
  repo_command_parameter_ = NULL;
  return temp;
}
inline void RepoCommandParameterMessage::set_allocated_repo_command_parameter(::ndn_message::RepoCommandParameterMessage_RepoCommandParameter* repo_command_parameter) {
  delete repo_command_parameter_;
  repo_command_parameter_ = repo_command_parameter;
  if (repo_command_parameter) {
    set_has_repo_command_parameter();
  } else {
    clear_has_repo_command_parameter();
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ndn_message

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_repo_2dcommand_2dparameter_2eproto__INCLUDED
