// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatbuf.proto

#ifndef PROTOBUF_chatbuf_2eproto__INCLUDED
#define PROTOBUF_chatbuf_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>
// For backwards compatibility with systems that install an older Protobuf (e.g. Ubuntu)),
//   include the older output from protoc so that the sample program compiles.
#if GOOGLE_PROTOBUF_VERSION < 2005000

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace SyncDemo {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_chatbuf_2eproto();
void protobuf_AssignDesc_chatbuf_2eproto();
void protobuf_ShutdownFile_chatbuf_2eproto();

class ChatMessage;

enum ChatMessage_ChatMessageType {
  ChatMessage_ChatMessageType_CHAT = 0,
  ChatMessage_ChatMessageType_HELLO = 1,
  ChatMessage_ChatMessageType_LEAVE = 2,
  ChatMessage_ChatMessageType_JOIN = 3,
  ChatMessage_ChatMessageType_OTHER = 4
};
bool ChatMessage_ChatMessageType_IsValid(int value);
const ChatMessage_ChatMessageType ChatMessage_ChatMessageType_ChatMessageType_MIN = ChatMessage_ChatMessageType_CHAT;
const ChatMessage_ChatMessageType ChatMessage_ChatMessageType_ChatMessageType_MAX = ChatMessage_ChatMessageType_OTHER;
const int ChatMessage_ChatMessageType_ChatMessageType_ARRAYSIZE = ChatMessage_ChatMessageType_ChatMessageType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ChatMessage_ChatMessageType_descriptor();
inline const ::std::string& ChatMessage_ChatMessageType_Name(ChatMessage_ChatMessageType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ChatMessage_ChatMessageType_descriptor(), value);
}
inline bool ChatMessage_ChatMessageType_Parse(
    const ::std::string& name, ChatMessage_ChatMessageType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ChatMessage_ChatMessageType>(
    ChatMessage_ChatMessageType_descriptor(), name, value);
}
// ===================================================================

class ChatMessage : public ::google::protobuf::Message {
 public:
  ChatMessage();
  virtual ~ChatMessage();
  
  ChatMessage(const ChatMessage& from);
  
  inline ChatMessage& operator=(const ChatMessage& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ChatMessage& default_instance();
  
  void Swap(ChatMessage* other);
  
  // implements Message ----------------------------------------------
  
  ChatMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ChatMessage& from);
  void MergeFrom(const ChatMessage& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef ChatMessage_ChatMessageType ChatMessageType;
  static const ChatMessageType CHAT = ChatMessage_ChatMessageType_CHAT;
  static const ChatMessageType HELLO = ChatMessage_ChatMessageType_HELLO;
  static const ChatMessageType LEAVE = ChatMessage_ChatMessageType_LEAVE;
  static const ChatMessageType JOIN = ChatMessage_ChatMessageType_JOIN;
  static const ChatMessageType OTHER = ChatMessage_ChatMessageType_OTHER;
  static inline bool ChatMessageType_IsValid(int value) {
    return ChatMessage_ChatMessageType_IsValid(value);
  }
  static const ChatMessageType ChatMessageType_MIN =
    ChatMessage_ChatMessageType_ChatMessageType_MIN;
  static const ChatMessageType ChatMessageType_MAX =
    ChatMessage_ChatMessageType_ChatMessageType_MAX;
  static const int ChatMessageType_ARRAYSIZE =
    ChatMessage_ChatMessageType_ChatMessageType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ChatMessageType_descriptor() {
    return ChatMessage_ChatMessageType_descriptor();
  }
  static inline const ::std::string& ChatMessageType_Name(ChatMessageType value) {
    return ChatMessage_ChatMessageType_Name(value);
  }
  static inline bool ChatMessageType_Parse(const ::std::string& name,
      ChatMessageType* value) {
    return ChatMessage_ChatMessageType_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required string to = 1;
  inline bool has_to() const;
  inline void clear_to();
  static const int kToFieldNumber = 1;
  inline const ::std::string& to() const;
  inline void set_to(const ::std::string& value);
  inline void set_to(const char* value);
  inline void set_to(const char* value, size_t size);
  inline ::std::string* mutable_to();
  inline ::std::string* release_to();
  
  // required string from = 2;
  inline bool has_from() const;
  inline void clear_from();
  static const int kFromFieldNumber = 2;
  inline const ::std::string& from() const;
  inline void set_from(const ::std::string& value);
  inline void set_from(const char* value);
  inline void set_from(const char* value, size_t size);
  inline ::std::string* mutable_from();
  inline ::std::string* release_from();
  
  // required .SyncDemo.ChatMessage.ChatMessageType type = 3 [default = CHAT];
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 3;
  inline ::SyncDemo::ChatMessage_ChatMessageType type() const;
  inline void set_type(::SyncDemo::ChatMessage_ChatMessageType value);
  
  // optional string data = 4;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 4;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const char* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  
  // required int32 timestamp = 5;
  inline bool has_timestamp() const;
  inline void clear_timestamp();
  static const int kTimestampFieldNumber = 5;
  inline ::google::protobuf::int32 timestamp() const;
  inline void set_timestamp(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:SyncDemo.ChatMessage)
 private:
  inline void set_has_to();
  inline void clear_has_to();
  inline void set_has_from();
  inline void clear_has_from();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_data();
  inline void clear_has_data();
  inline void set_has_timestamp();
  inline void clear_has_timestamp();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* to_;
  ::std::string* from_;
  ::std::string* data_;
  int type_;
  ::google::protobuf::int32 timestamp_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];
  
  friend void  protobuf_AddDesc_chatbuf_2eproto();
  friend void protobuf_AssignDesc_chatbuf_2eproto();
  friend void protobuf_ShutdownFile_chatbuf_2eproto();
  
  void InitAsDefaultInstance();
  static ChatMessage* default_instance_;
};
// ===================================================================


// ===================================================================

// ChatMessage

// required string to = 1;
inline bool ChatMessage::has_to() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ChatMessage::set_has_to() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ChatMessage::clear_has_to() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ChatMessage::clear_to() {
  if (to_ != &::google::protobuf::internal::kEmptyString) {
    to_->clear();
  }
  clear_has_to();
}
inline const ::std::string& ChatMessage::to() const {
  return *to_;
}
inline void ChatMessage::set_to(const ::std::string& value) {
  set_has_to();
  if (to_ == &::google::protobuf::internal::kEmptyString) {
    to_ = new ::std::string;
  }
  to_->assign(value);
}
inline void ChatMessage::set_to(const char* value) {
  set_has_to();
  if (to_ == &::google::protobuf::internal::kEmptyString) {
    to_ = new ::std::string;
  }
  to_->assign(value);
}
inline void ChatMessage::set_to(const char* value, size_t size) {
  set_has_to();
  if (to_ == &::google::protobuf::internal::kEmptyString) {
    to_ = new ::std::string;
  }
  to_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ChatMessage::mutable_to() {
  set_has_to();
  if (to_ == &::google::protobuf::internal::kEmptyString) {
    to_ = new ::std::string;
  }
  return to_;
}
inline ::std::string* ChatMessage::release_to() {
  clear_has_to();
  if (to_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = to_;
    to_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required string from = 2;
inline bool ChatMessage::has_from() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ChatMessage::set_has_from() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ChatMessage::clear_has_from() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ChatMessage::clear_from() {
  if (from_ != &::google::protobuf::internal::kEmptyString) {
    from_->clear();
  }
  clear_has_from();
}
inline const ::std::string& ChatMessage::from() const {
  return *from_;
}
inline void ChatMessage::set_from(const ::std::string& value) {
  set_has_from();
  if (from_ == &::google::protobuf::internal::kEmptyString) {
    from_ = new ::std::string;
  }
  from_->assign(value);
}
inline void ChatMessage::set_from(const char* value) {
  set_has_from();
  if (from_ == &::google::protobuf::internal::kEmptyString) {
    from_ = new ::std::string;
  }
  from_->assign(value);
}
inline void ChatMessage::set_from(const char* value, size_t size) {
  set_has_from();
  if (from_ == &::google::protobuf::internal::kEmptyString) {
    from_ = new ::std::string;
  }
  from_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ChatMessage::mutable_from() {
  set_has_from();
  if (from_ == &::google::protobuf::internal::kEmptyString) {
    from_ = new ::std::string;
  }
  return from_;
}
inline ::std::string* ChatMessage::release_from() {
  clear_has_from();
  if (from_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = from_;
    from_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required .SyncDemo.ChatMessage.ChatMessageType type = 3 [default = CHAT];
inline bool ChatMessage::has_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ChatMessage::set_has_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ChatMessage::clear_has_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ChatMessage::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::SyncDemo::ChatMessage_ChatMessageType ChatMessage::type() const {
  return static_cast< ::SyncDemo::ChatMessage_ChatMessageType >(type_);
}
inline void ChatMessage::set_type(::SyncDemo::ChatMessage_ChatMessageType value) {
  GOOGLE_DCHECK(::SyncDemo::ChatMessage_ChatMessageType_IsValid(value));
  set_has_type();
  type_ = value;
}

// optional string data = 4;
inline bool ChatMessage::has_data() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ChatMessage::set_has_data() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ChatMessage::clear_has_data() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ChatMessage::clear_data() {
  if (data_ != &::google::protobuf::internal::kEmptyString) {
    data_->clear();
  }
  clear_has_data();
}
inline const ::std::string& ChatMessage::data() const {
  return *data_;
}
inline void ChatMessage::set_data(const ::std::string& value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(value);
}
inline void ChatMessage::set_data(const char* value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(value);
}
inline void ChatMessage::set_data(const char* value, size_t size) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ChatMessage::mutable_data() {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  return data_;
}
inline ::std::string* ChatMessage::release_data() {
  clear_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = data_;
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required int32 timestamp = 5;
inline bool ChatMessage::has_timestamp() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ChatMessage::set_has_timestamp() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ChatMessage::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ChatMessage::clear_timestamp() {
  timestamp_ = 0;
  clear_has_timestamp();
}
inline ::google::protobuf::int32 ChatMessage::timestamp() const {
  return timestamp_;
}
inline void ChatMessage::set_timestamp(::google::protobuf::int32 value) {
  set_has_timestamp();
  timestamp_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace SyncDemo

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::SyncDemo::ChatMessage_ChatMessageType>() {
  return ::SyncDemo::ChatMessage_ChatMessageType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#elif GOOGLE_PROTOBUF_VERSION < 2006000

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace SyncDemo {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_chatbuf_2eproto();
void protobuf_AssignDesc_chatbuf_2eproto();
void protobuf_ShutdownFile_chatbuf_2eproto();

class ChatMessage;

enum ChatMessage_ChatMessageType {
  ChatMessage_ChatMessageType_CHAT = 0,
  ChatMessage_ChatMessageType_HELLO = 1,
  ChatMessage_ChatMessageType_LEAVE = 2,
  ChatMessage_ChatMessageType_JOIN = 3,
  ChatMessage_ChatMessageType_OTHER = 4
};
bool ChatMessage_ChatMessageType_IsValid(int value);
const ChatMessage_ChatMessageType ChatMessage_ChatMessageType_ChatMessageType_MIN = ChatMessage_ChatMessageType_CHAT;
const ChatMessage_ChatMessageType ChatMessage_ChatMessageType_ChatMessageType_MAX = ChatMessage_ChatMessageType_OTHER;
const int ChatMessage_ChatMessageType_ChatMessageType_ARRAYSIZE = ChatMessage_ChatMessageType_ChatMessageType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ChatMessage_ChatMessageType_descriptor();
inline const ::std::string& ChatMessage_ChatMessageType_Name(ChatMessage_ChatMessageType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ChatMessage_ChatMessageType_descriptor(), value);
}
inline bool ChatMessage_ChatMessageType_Parse(
    const ::std::string& name, ChatMessage_ChatMessageType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ChatMessage_ChatMessageType>(
    ChatMessage_ChatMessageType_descriptor(), name, value);
}
// ===================================================================

class ChatMessage : public ::google::protobuf::Message {
 public:
  ChatMessage();
  virtual ~ChatMessage();

  ChatMessage(const ChatMessage& from);

  inline ChatMessage& operator=(const ChatMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ChatMessage& default_instance();

  void Swap(ChatMessage* other);

  // implements Message ----------------------------------------------

  ChatMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ChatMessage& from);
  void MergeFrom(const ChatMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef ChatMessage_ChatMessageType ChatMessageType;
  static const ChatMessageType CHAT = ChatMessage_ChatMessageType_CHAT;
  static const ChatMessageType HELLO = ChatMessage_ChatMessageType_HELLO;
  static const ChatMessageType LEAVE = ChatMessage_ChatMessageType_LEAVE;
  static const ChatMessageType JOIN = ChatMessage_ChatMessageType_JOIN;
  static const ChatMessageType OTHER = ChatMessage_ChatMessageType_OTHER;
  static inline bool ChatMessageType_IsValid(int value) {
    return ChatMessage_ChatMessageType_IsValid(value);
  }
  static const ChatMessageType ChatMessageType_MIN =
    ChatMessage_ChatMessageType_ChatMessageType_MIN;
  static const ChatMessageType ChatMessageType_MAX =
    ChatMessage_ChatMessageType_ChatMessageType_MAX;
  static const int ChatMessageType_ARRAYSIZE =
    ChatMessage_ChatMessageType_ChatMessageType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ChatMessageType_descriptor() {
    return ChatMessage_ChatMessageType_descriptor();
  }
  static inline const ::std::string& ChatMessageType_Name(ChatMessageType value) {
    return ChatMessage_ChatMessageType_Name(value);
  }
  static inline bool ChatMessageType_Parse(const ::std::string& name,
      ChatMessageType* value) {
    return ChatMessage_ChatMessageType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required string to = 1;
  inline bool has_to() const;
  inline void clear_to();
  static const int kToFieldNumber = 1;
  inline const ::std::string& to() const;
  inline void set_to(const ::std::string& value);
  inline void set_to(const char* value);
  inline void set_to(const char* value, size_t size);
  inline ::std::string* mutable_to();
  inline ::std::string* release_to();
  inline void set_allocated_to(::std::string* to);

  // required string from = 2;
  inline bool has_from() const;
  inline void clear_from();
  static const int kFromFieldNumber = 2;
  inline const ::std::string& from() const;
  inline void set_from(const ::std::string& value);
  inline void set_from(const char* value);
  inline void set_from(const char* value, size_t size);
  inline ::std::string* mutable_from();
  inline ::std::string* release_from();
  inline void set_allocated_from(::std::string* from);

  // required .SyncDemo.ChatMessage.ChatMessageType type = 3 [default = CHAT];
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 3;
  inline ::SyncDemo::ChatMessage_ChatMessageType type() const;
  inline void set_type(::SyncDemo::ChatMessage_ChatMessageType value);

  // optional string data = 4;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 4;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const char* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  inline void set_allocated_data(::std::string* data);

  // required int32 timestamp = 5;
  inline bool has_timestamp() const;
  inline void clear_timestamp();
  static const int kTimestampFieldNumber = 5;
  inline ::google::protobuf::int32 timestamp() const;
  inline void set_timestamp(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:SyncDemo.ChatMessage)
 private:
  inline void set_has_to();
  inline void clear_has_to();
  inline void set_has_from();
  inline void clear_has_from();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_data();
  inline void clear_has_data();
  inline void set_has_timestamp();
  inline void clear_has_timestamp();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* to_;
  ::std::string* from_;
  ::std::string* data_;
  int type_;
  ::google::protobuf::int32 timestamp_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_chatbuf_2eproto();
  friend void protobuf_AssignDesc_chatbuf_2eproto();
  friend void protobuf_ShutdownFile_chatbuf_2eproto();

  void InitAsDefaultInstance();
  static ChatMessage* default_instance_;
};
// ===================================================================


// ===================================================================

// ChatMessage

// required string to = 1;
inline bool ChatMessage::has_to() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ChatMessage::set_has_to() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ChatMessage::clear_has_to() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ChatMessage::clear_to() {
  if (to_ != &::google::protobuf::internal::kEmptyString) {
    to_->clear();
  }
  clear_has_to();
}
inline const ::std::string& ChatMessage::to() const {
  return *to_;
}
inline void ChatMessage::set_to(const ::std::string& value) {
  set_has_to();
  if (to_ == &::google::protobuf::internal::kEmptyString) {
    to_ = new ::std::string;
  }
  to_->assign(value);
}
inline void ChatMessage::set_to(const char* value) {
  set_has_to();
  if (to_ == &::google::protobuf::internal::kEmptyString) {
    to_ = new ::std::string;
  }
  to_->assign(value);
}
inline void ChatMessage::set_to(const char* value, size_t size) {
  set_has_to();
  if (to_ == &::google::protobuf::internal::kEmptyString) {
    to_ = new ::std::string;
  }
  to_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ChatMessage::mutable_to() {
  set_has_to();
  if (to_ == &::google::protobuf::internal::kEmptyString) {
    to_ = new ::std::string;
  }
  return to_;
}
inline ::std::string* ChatMessage::release_to() {
  clear_has_to();
  if (to_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = to_;
    to_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void ChatMessage::set_allocated_to(::std::string* to) {
  if (to_ != &::google::protobuf::internal::kEmptyString) {
    delete to_;
  }
  if (to) {
    set_has_to();
    to_ = to;
  } else {
    clear_has_to();
    to_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required string from = 2;
inline bool ChatMessage::has_from() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ChatMessage::set_has_from() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ChatMessage::clear_has_from() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ChatMessage::clear_from() {
  if (from_ != &::google::protobuf::internal::kEmptyString) {
    from_->clear();
  }
  clear_has_from();
}
inline const ::std::string& ChatMessage::from() const {
  return *from_;
}
inline void ChatMessage::set_from(const ::std::string& value) {
  set_has_from();
  if (from_ == &::google::protobuf::internal::kEmptyString) {
    from_ = new ::std::string;
  }
  from_->assign(value);
}
inline void ChatMessage::set_from(const char* value) {
  set_has_from();
  if (from_ == &::google::protobuf::internal::kEmptyString) {
    from_ = new ::std::string;
  }
  from_->assign(value);
}
inline void ChatMessage::set_from(const char* value, size_t size) {
  set_has_from();
  if (from_ == &::google::protobuf::internal::kEmptyString) {
    from_ = new ::std::string;
  }
  from_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ChatMessage::mutable_from() {
  set_has_from();
  if (from_ == &::google::protobuf::internal::kEmptyString) {
    from_ = new ::std::string;
  }
  return from_;
}
inline ::std::string* ChatMessage::release_from() {
  clear_has_from();
  if (from_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = from_;
    from_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void ChatMessage::set_allocated_from(::std::string* from) {
  if (from_ != &::google::protobuf::internal::kEmptyString) {
    delete from_;
  }
  if (from) {
    set_has_from();
    from_ = from;
  } else {
    clear_has_from();
    from_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required .SyncDemo.ChatMessage.ChatMessageType type = 3 [default = CHAT];
inline bool ChatMessage::has_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ChatMessage::set_has_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ChatMessage::clear_has_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ChatMessage::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::SyncDemo::ChatMessage_ChatMessageType ChatMessage::type() const {
  return static_cast< ::SyncDemo::ChatMessage_ChatMessageType >(type_);
}
inline void ChatMessage::set_type(::SyncDemo::ChatMessage_ChatMessageType value) {
  assert(::SyncDemo::ChatMessage_ChatMessageType_IsValid(value));
  set_has_type();
  type_ = value;
}

// optional string data = 4;
inline bool ChatMessage::has_data() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ChatMessage::set_has_data() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ChatMessage::clear_has_data() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ChatMessage::clear_data() {
  if (data_ != &::google::protobuf::internal::kEmptyString) {
    data_->clear();
  }
  clear_has_data();
}
inline const ::std::string& ChatMessage::data() const {
  return *data_;
}
inline void ChatMessage::set_data(const ::std::string& value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(value);
}
inline void ChatMessage::set_data(const char* value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(value);
}
inline void ChatMessage::set_data(const char* value, size_t size) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ChatMessage::mutable_data() {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  return data_;
}
inline ::std::string* ChatMessage::release_data() {
  clear_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = data_;
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void ChatMessage::set_allocated_data(::std::string* data) {
  if (data_ != &::google::protobuf::internal::kEmptyString) {
    delete data_;
  }
  if (data) {
    set_has_data();
    data_ = data;
  } else {
    clear_has_data();
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required int32 timestamp = 5;
inline bool ChatMessage::has_timestamp() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ChatMessage::set_has_timestamp() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ChatMessage::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ChatMessage::clear_timestamp() {
  timestamp_ = 0;
  clear_has_timestamp();
}
inline ::google::protobuf::int32 ChatMessage::timestamp() const {
  return timestamp_;
}
inline void ChatMessage::set_timestamp(::google::protobuf::int32 value) {
  set_has_timestamp();
  timestamp_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace SyncDemo

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::SyncDemo::ChatMessage_ChatMessageType>() {
  return ::SyncDemo::ChatMessage_ChatMessageType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#elif GOOGLE_PROTOBUF_VERSION < 3000000

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace SyncDemo {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_chatbuf_2eproto();
void protobuf_AssignDesc_chatbuf_2eproto();
void protobuf_ShutdownFile_chatbuf_2eproto();

class ChatMessage;

enum ChatMessage_ChatMessageType {
  ChatMessage_ChatMessageType_CHAT = 0,
  ChatMessage_ChatMessageType_HELLO = 1,
  ChatMessage_ChatMessageType_LEAVE = 2,
  ChatMessage_ChatMessageType_JOIN = 3,
  ChatMessage_ChatMessageType_OTHER = 4
};
bool ChatMessage_ChatMessageType_IsValid(int value);
const ChatMessage_ChatMessageType ChatMessage_ChatMessageType_ChatMessageType_MIN = ChatMessage_ChatMessageType_CHAT;
const ChatMessage_ChatMessageType ChatMessage_ChatMessageType_ChatMessageType_MAX = ChatMessage_ChatMessageType_OTHER;
const int ChatMessage_ChatMessageType_ChatMessageType_ARRAYSIZE = ChatMessage_ChatMessageType_ChatMessageType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ChatMessage_ChatMessageType_descriptor();
inline const ::std::string& ChatMessage_ChatMessageType_Name(ChatMessage_ChatMessageType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ChatMessage_ChatMessageType_descriptor(), value);
}
inline bool ChatMessage_ChatMessageType_Parse(
    const ::std::string& name, ChatMessage_ChatMessageType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ChatMessage_ChatMessageType>(
    ChatMessage_ChatMessageType_descriptor(), name, value);
}
// ===================================================================

class ChatMessage : public ::google::protobuf::Message {
 public:
  ChatMessage();
  virtual ~ChatMessage();

  ChatMessage(const ChatMessage& from);

  inline ChatMessage& operator=(const ChatMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ChatMessage& default_instance();

  void Swap(ChatMessage* other);

  // implements Message ----------------------------------------------

  ChatMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ChatMessage& from);
  void MergeFrom(const ChatMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef ChatMessage_ChatMessageType ChatMessageType;
  static const ChatMessageType CHAT = ChatMessage_ChatMessageType_CHAT;
  static const ChatMessageType HELLO = ChatMessage_ChatMessageType_HELLO;
  static const ChatMessageType LEAVE = ChatMessage_ChatMessageType_LEAVE;
  static const ChatMessageType JOIN = ChatMessage_ChatMessageType_JOIN;
  static const ChatMessageType OTHER = ChatMessage_ChatMessageType_OTHER;
  static inline bool ChatMessageType_IsValid(int value) {
    return ChatMessage_ChatMessageType_IsValid(value);
  }
  static const ChatMessageType ChatMessageType_MIN =
    ChatMessage_ChatMessageType_ChatMessageType_MIN;
  static const ChatMessageType ChatMessageType_MAX =
    ChatMessage_ChatMessageType_ChatMessageType_MAX;
  static const int ChatMessageType_ARRAYSIZE =
    ChatMessage_ChatMessageType_ChatMessageType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ChatMessageType_descriptor() {
    return ChatMessage_ChatMessageType_descriptor();
  }
  static inline const ::std::string& ChatMessageType_Name(ChatMessageType value) {
    return ChatMessage_ChatMessageType_Name(value);
  }
  static inline bool ChatMessageType_Parse(const ::std::string& name,
      ChatMessageType* value) {
    return ChatMessage_ChatMessageType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required string to = 1;
  inline bool has_to() const;
  inline void clear_to();
  static const int kToFieldNumber = 1;
  inline const ::std::string& to() const;
  inline void set_to(const ::std::string& value);
  inline void set_to(const char* value);
  inline void set_to(const char* value, size_t size);
  inline ::std::string* mutable_to();
  inline ::std::string* release_to();
  inline void set_allocated_to(::std::string* to);

  // required string from = 2;
  inline bool has_from() const;
  inline void clear_from();
  static const int kFromFieldNumber = 2;
  inline const ::std::string& from() const;
  inline void set_from(const ::std::string& value);
  inline void set_from(const char* value);
  inline void set_from(const char* value, size_t size);
  inline ::std::string* mutable_from();
  inline ::std::string* release_from();
  inline void set_allocated_from(::std::string* from);

  // required .SyncDemo.ChatMessage.ChatMessageType type = 3 [default = CHAT];
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 3;
  inline ::SyncDemo::ChatMessage_ChatMessageType type() const;
  inline void set_type(::SyncDemo::ChatMessage_ChatMessageType value);

  // optional string data = 4;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 4;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const char* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  inline void set_allocated_data(::std::string* data);

  // required int32 timestamp = 5;
  inline bool has_timestamp() const;
  inline void clear_timestamp();
  static const int kTimestampFieldNumber = 5;
  inline ::google::protobuf::int32 timestamp() const;
  inline void set_timestamp(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:SyncDemo.ChatMessage)
 private:
  inline void set_has_to();
  inline void clear_has_to();
  inline void set_has_from();
  inline void clear_has_from();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_data();
  inline void clear_has_data();
  inline void set_has_timestamp();
  inline void clear_has_timestamp();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* to_;
  ::std::string* from_;
  ::std::string* data_;
  int type_;
  ::google::protobuf::int32 timestamp_;
  friend void  protobuf_AddDesc_chatbuf_2eproto();
  friend void protobuf_AssignDesc_chatbuf_2eproto();
  friend void protobuf_ShutdownFile_chatbuf_2eproto();

  void InitAsDefaultInstance();
  static ChatMessage* default_instance_;
};
// ===================================================================


// ===================================================================

// ChatMessage

// required string to = 1;
inline bool ChatMessage::has_to() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ChatMessage::set_has_to() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ChatMessage::clear_has_to() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ChatMessage::clear_to() {
  if (to_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    to_->clear();
  }
  clear_has_to();
}
inline const ::std::string& ChatMessage::to() const {
  // @@protoc_insertion_point(field_get:SyncDemo.ChatMessage.to)
  return *to_;
}
inline void ChatMessage::set_to(const ::std::string& value) {
  set_has_to();
  if (to_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    to_ = new ::std::string;
  }
  to_->assign(value);
  // @@protoc_insertion_point(field_set:SyncDemo.ChatMessage.to)
}
inline void ChatMessage::set_to(const char* value) {
  set_has_to();
  if (to_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    to_ = new ::std::string;
  }
  to_->assign(value);
  // @@protoc_insertion_point(field_set_char:SyncDemo.ChatMessage.to)
}
inline void ChatMessage::set_to(const char* value, size_t size) {
  set_has_to();
  if (to_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    to_ = new ::std::string;
  }
  to_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:SyncDemo.ChatMessage.to)
}
inline ::std::string* ChatMessage::mutable_to() {
  set_has_to();
  if (to_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    to_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:SyncDemo.ChatMessage.to)
  return to_;
}
inline ::std::string* ChatMessage::release_to() {
  clear_has_to();
  if (to_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = to_;
    to_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ChatMessage::set_allocated_to(::std::string* to) {
  if (to_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete to_;
  }
  if (to) {
    set_has_to();
    to_ = to;
  } else {
    clear_has_to();
    to_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:SyncDemo.ChatMessage.to)
}

// required string from = 2;
inline bool ChatMessage::has_from() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ChatMessage::set_has_from() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ChatMessage::clear_has_from() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ChatMessage::clear_from() {
  if (from_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    from_->clear();
  }
  clear_has_from();
}
inline const ::std::string& ChatMessage::from() const {
  // @@protoc_insertion_point(field_get:SyncDemo.ChatMessage.from)
  return *from_;
}
inline void ChatMessage::set_from(const ::std::string& value) {
  set_has_from();
  if (from_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    from_ = new ::std::string;
  }
  from_->assign(value);
  // @@protoc_insertion_point(field_set:SyncDemo.ChatMessage.from)
}
inline void ChatMessage::set_from(const char* value) {
  set_has_from();
  if (from_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    from_ = new ::std::string;
  }
  from_->assign(value);
  // @@protoc_insertion_point(field_set_char:SyncDemo.ChatMessage.from)
}
inline void ChatMessage::set_from(const char* value, size_t size) {
  set_has_from();
  if (from_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    from_ = new ::std::string;
  }
  from_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:SyncDemo.ChatMessage.from)
}
inline ::std::string* ChatMessage::mutable_from() {
  set_has_from();
  if (from_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    from_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:SyncDemo.ChatMessage.from)
  return from_;
}
inline ::std::string* ChatMessage::release_from() {
  clear_has_from();
  if (from_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = from_;
    from_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ChatMessage::set_allocated_from(::std::string* from) {
  if (from_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete from_;
  }
  if (from) {
    set_has_from();
    from_ = from;
  } else {
    clear_has_from();
    from_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:SyncDemo.ChatMessage.from)
}

// required .SyncDemo.ChatMessage.ChatMessageType type = 3 [default = CHAT];
inline bool ChatMessage::has_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ChatMessage::set_has_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ChatMessage::clear_has_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ChatMessage::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::SyncDemo::ChatMessage_ChatMessageType ChatMessage::type() const {
  // @@protoc_insertion_point(field_get:SyncDemo.ChatMessage.type)
  return static_cast< ::SyncDemo::ChatMessage_ChatMessageType >(type_);
}
inline void ChatMessage::set_type(::SyncDemo::ChatMessage_ChatMessageType value) {
  assert(::SyncDemo::ChatMessage_ChatMessageType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:SyncDemo.ChatMessage.type)
}

// optional string data = 4;
inline bool ChatMessage::has_data() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ChatMessage::set_has_data() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ChatMessage::clear_has_data() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ChatMessage::clear_data() {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_->clear();
  }
  clear_has_data();
}
inline const ::std::string& ChatMessage::data() const {
  // @@protoc_insertion_point(field_get:SyncDemo.ChatMessage.data)
  return *data_;
}
inline void ChatMessage::set_data(const ::std::string& value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set:SyncDemo.ChatMessage.data)
}
inline void ChatMessage::set_data(const char* value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set_char:SyncDemo.ChatMessage.data)
}
inline void ChatMessage::set_data(const char* value, size_t size) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:SyncDemo.ChatMessage.data)
}
inline ::std::string* ChatMessage::mutable_data() {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:SyncDemo.ChatMessage.data)
  return data_;
}
inline ::std::string* ChatMessage::release_data() {
  clear_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = data_;
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ChatMessage::set_allocated_data(::std::string* data) {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete data_;
  }
  if (data) {
    set_has_data();
    data_ = data;
  } else {
    clear_has_data();
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:SyncDemo.ChatMessage.data)
}

// required int32 timestamp = 5;
inline bool ChatMessage::has_timestamp() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ChatMessage::set_has_timestamp() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ChatMessage::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ChatMessage::clear_timestamp() {
  timestamp_ = 0;
  clear_has_timestamp();
}
inline ::google::protobuf::int32 ChatMessage::timestamp() const {
  // @@protoc_insertion_point(field_get:SyncDemo.ChatMessage.timestamp)
  return timestamp_;
}
inline void ChatMessage::set_timestamp(::google::protobuf::int32 value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:SyncDemo.ChatMessage.timestamp)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace SyncDemo

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::SyncDemo::ChatMessage_ChatMessageType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::SyncDemo::ChatMessage_ChatMessageType>() {
  return ::SyncDemo::ChatMessage_ChatMessageType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#else // GOOGLE_PROTOBUF_VERSION < 3000000

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace SyncDemo {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_chatbuf_2eproto();
void protobuf_AssignDesc_chatbuf_2eproto();
void protobuf_ShutdownFile_chatbuf_2eproto();

class ChatMessage;

enum ChatMessage_ChatMessageType {
  ChatMessage_ChatMessageType_CHAT = 0,
  ChatMessage_ChatMessageType_HELLO = 1,
  ChatMessage_ChatMessageType_LEAVE = 2,
  ChatMessage_ChatMessageType_JOIN = 3,
  ChatMessage_ChatMessageType_OTHER = 4
};
bool ChatMessage_ChatMessageType_IsValid(int value);
const ChatMessage_ChatMessageType ChatMessage_ChatMessageType_ChatMessageType_MIN = ChatMessage_ChatMessageType_CHAT;
const ChatMessage_ChatMessageType ChatMessage_ChatMessageType_ChatMessageType_MAX = ChatMessage_ChatMessageType_OTHER;
const int ChatMessage_ChatMessageType_ChatMessageType_ARRAYSIZE = ChatMessage_ChatMessageType_ChatMessageType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ChatMessage_ChatMessageType_descriptor();
inline const ::std::string& ChatMessage_ChatMessageType_Name(ChatMessage_ChatMessageType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ChatMessage_ChatMessageType_descriptor(), value);
}
inline bool ChatMessage_ChatMessageType_Parse(
    const ::std::string& name, ChatMessage_ChatMessageType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ChatMessage_ChatMessageType>(
    ChatMessage_ChatMessageType_descriptor(), name, value);
}
// ===================================================================

class ChatMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SyncDemo.ChatMessage) */ {
 public:
  ChatMessage();
  virtual ~ChatMessage();

  ChatMessage(const ChatMessage& from);

  inline ChatMessage& operator=(const ChatMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ChatMessage& default_instance();

  void Swap(ChatMessage* other);

  // implements Message ----------------------------------------------

  inline ChatMessage* New() const { return New(NULL); }

  ChatMessage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ChatMessage& from);
  void MergeFrom(const ChatMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ChatMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef ChatMessage_ChatMessageType ChatMessageType;
  static const ChatMessageType CHAT =
    ChatMessage_ChatMessageType_CHAT;
  static const ChatMessageType HELLO =
    ChatMessage_ChatMessageType_HELLO;
  static const ChatMessageType LEAVE =
    ChatMessage_ChatMessageType_LEAVE;
  static const ChatMessageType JOIN =
    ChatMessage_ChatMessageType_JOIN;
  static const ChatMessageType OTHER =
    ChatMessage_ChatMessageType_OTHER;
  static inline bool ChatMessageType_IsValid(int value) {
    return ChatMessage_ChatMessageType_IsValid(value);
  }
  static const ChatMessageType ChatMessageType_MIN =
    ChatMessage_ChatMessageType_ChatMessageType_MIN;
  static const ChatMessageType ChatMessageType_MAX =
    ChatMessage_ChatMessageType_ChatMessageType_MAX;
  static const int ChatMessageType_ARRAYSIZE =
    ChatMessage_ChatMessageType_ChatMessageType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ChatMessageType_descriptor() {
    return ChatMessage_ChatMessageType_descriptor();
  }
  static inline const ::std::string& ChatMessageType_Name(ChatMessageType value) {
    return ChatMessage_ChatMessageType_Name(value);
  }
  static inline bool ChatMessageType_Parse(const ::std::string& name,
      ChatMessageType* value) {
    return ChatMessage_ChatMessageType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required string to = 1;
  bool has_to() const;
  void clear_to();
  static const int kToFieldNumber = 1;
  const ::std::string& to() const;
  void set_to(const ::std::string& value);
  void set_to(const char* value);
  void set_to(const char* value, size_t size);
  ::std::string* mutable_to();
  ::std::string* release_to();
  void set_allocated_to(::std::string* to);

  // required string from = 2;
  bool has_from() const;
  void clear_from();
  static const int kFromFieldNumber = 2;
  const ::std::string& from() const;
  void set_from(const ::std::string& value);
  void set_from(const char* value);
  void set_from(const char* value, size_t size);
  ::std::string* mutable_from();
  ::std::string* release_from();
  void set_allocated_from(::std::string* from);

  // required .SyncDemo.ChatMessage.ChatMessageType type = 3 [default = CHAT];
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 3;
  ::SyncDemo::ChatMessage_ChatMessageType type() const;
  void set_type(::SyncDemo::ChatMessage_ChatMessageType value);

  // optional string data = 4;
  bool has_data() const;
  void clear_data();
  static const int kDataFieldNumber = 4;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  void set_data(const char* value);
  void set_data(const char* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // required int32 timestamp = 5;
  bool has_timestamp() const;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 5;
  ::google::protobuf::int32 timestamp() const;
  void set_timestamp(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:SyncDemo.ChatMessage)
 private:
  inline void set_has_to();
  inline void clear_has_to();
  inline void set_has_from();
  inline void clear_has_from();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_data();
  inline void clear_has_data();
  inline void set_has_timestamp();
  inline void clear_has_timestamp();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr to_;
  ::google::protobuf::internal::ArenaStringPtr from_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  int type_;
  ::google::protobuf::int32 timestamp_;
  friend void  protobuf_AddDesc_chatbuf_2eproto();
  friend void protobuf_AssignDesc_chatbuf_2eproto();
  friend void protobuf_ShutdownFile_chatbuf_2eproto();

  void InitAsDefaultInstance();
  static ChatMessage* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ChatMessage

// required string to = 1;
inline bool ChatMessage::has_to() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ChatMessage::set_has_to() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ChatMessage::clear_has_to() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ChatMessage::clear_to() {
  to_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_to();
}
inline const ::std::string& ChatMessage::to() const {
  // @@protoc_insertion_point(field_get:SyncDemo.ChatMessage.to)
  return to_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ChatMessage::set_to(const ::std::string& value) {
  set_has_to();
  to_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:SyncDemo.ChatMessage.to)
}
inline void ChatMessage::set_to(const char* value) {
  set_has_to();
  to_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:SyncDemo.ChatMessage.to)
}
inline void ChatMessage::set_to(const char* value, size_t size) {
  set_has_to();
  to_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:SyncDemo.ChatMessage.to)
}
inline ::std::string* ChatMessage::mutable_to() {
  set_has_to();
  // @@protoc_insertion_point(field_mutable:SyncDemo.ChatMessage.to)
  return to_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ChatMessage::release_to() {
  // @@protoc_insertion_point(field_release:SyncDemo.ChatMessage.to)
  clear_has_to();
  return to_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ChatMessage::set_allocated_to(::std::string* to) {
  if (to != NULL) {
    set_has_to();
  } else {
    clear_has_to();
  }
  to_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), to);
  // @@protoc_insertion_point(field_set_allocated:SyncDemo.ChatMessage.to)
}

// required string from = 2;
inline bool ChatMessage::has_from() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ChatMessage::set_has_from() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ChatMessage::clear_has_from() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ChatMessage::clear_from() {
  from_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_from();
}
inline const ::std::string& ChatMessage::from() const {
  // @@protoc_insertion_point(field_get:SyncDemo.ChatMessage.from)
  return from_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ChatMessage::set_from(const ::std::string& value) {
  set_has_from();
  from_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:SyncDemo.ChatMessage.from)
}
inline void ChatMessage::set_from(const char* value) {
  set_has_from();
  from_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:SyncDemo.ChatMessage.from)
}
inline void ChatMessage::set_from(const char* value, size_t size) {
  set_has_from();
  from_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:SyncDemo.ChatMessage.from)
}
inline ::std::string* ChatMessage::mutable_from() {
  set_has_from();
  // @@protoc_insertion_point(field_mutable:SyncDemo.ChatMessage.from)
  return from_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ChatMessage::release_from() {
  // @@protoc_insertion_point(field_release:SyncDemo.ChatMessage.from)
  clear_has_from();
  return from_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ChatMessage::set_allocated_from(::std::string* from) {
  if (from != NULL) {
    set_has_from();
  } else {
    clear_has_from();
  }
  from_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from);
  // @@protoc_insertion_point(field_set_allocated:SyncDemo.ChatMessage.from)
}

// required .SyncDemo.ChatMessage.ChatMessageType type = 3 [default = CHAT];
inline bool ChatMessage::has_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ChatMessage::set_has_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ChatMessage::clear_has_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ChatMessage::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::SyncDemo::ChatMessage_ChatMessageType ChatMessage::type() const {
  // @@protoc_insertion_point(field_get:SyncDemo.ChatMessage.type)
  return static_cast< ::SyncDemo::ChatMessage_ChatMessageType >(type_);
}
inline void ChatMessage::set_type(::SyncDemo::ChatMessage_ChatMessageType value) {
  assert(::SyncDemo::ChatMessage_ChatMessageType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:SyncDemo.ChatMessage.type)
}

// optional string data = 4;
inline bool ChatMessage::has_data() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ChatMessage::set_has_data() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ChatMessage::clear_has_data() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ChatMessage::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_data();
}
inline const ::std::string& ChatMessage::data() const {
  // @@protoc_insertion_point(field_get:SyncDemo.ChatMessage.data)
  return data_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ChatMessage::set_data(const ::std::string& value) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:SyncDemo.ChatMessage.data)
}
inline void ChatMessage::set_data(const char* value) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:SyncDemo.ChatMessage.data)
}
inline void ChatMessage::set_data(const char* value, size_t size) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:SyncDemo.ChatMessage.data)
}
inline ::std::string* ChatMessage::mutable_data() {
  set_has_data();
  // @@protoc_insertion_point(field_mutable:SyncDemo.ChatMessage.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ChatMessage::release_data() {
  // @@protoc_insertion_point(field_release:SyncDemo.ChatMessage.data)
  clear_has_data();
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ChatMessage::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    set_has_data();
  } else {
    clear_has_data();
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:SyncDemo.ChatMessage.data)
}

// required int32 timestamp = 5;
inline bool ChatMessage::has_timestamp() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ChatMessage::set_has_timestamp() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ChatMessage::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ChatMessage::clear_timestamp() {
  timestamp_ = 0;
  clear_has_timestamp();
}
inline ::google::protobuf::int32 ChatMessage::timestamp() const {
  // @@protoc_insertion_point(field_get:SyncDemo.ChatMessage.timestamp)
  return timestamp_;
}
inline void ChatMessage::set_timestamp(::google::protobuf::int32 value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:SyncDemo.ChatMessage.timestamp)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace SyncDemo

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::SyncDemo::ChatMessage_ChatMessageType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::SyncDemo::ChatMessage_ChatMessageType>() {
  return ::SyncDemo::ChatMessage_ChatMessageType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif // GOOGLE_PROTOBUF_VERSION < 3000000

#endif  // PROTOBUF_chatbuf_2eproto__INCLUDED
