// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: face-query-filter.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "face-query-filter.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ndn_message {

namespace {

const ::google::protobuf::Descriptor* FaceQueryFilterMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  FaceQueryFilterMessage_reflection_ = NULL;
const ::google::protobuf::Descriptor* FaceQueryFilterMessage_FaceQueryFilter_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  FaceQueryFilterMessage_FaceQueryFilter_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* FaceQueryFilterMessage_FaceScope_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* FaceQueryFilterMessage_FacePersistency_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* FaceQueryFilterMessage_LinkType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_face_2dquery_2dfilter_2eproto() {
  protobuf_AddDesc_face_2dquery_2dfilter_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "face-query-filter.proto");
  GOOGLE_CHECK(file != NULL);
  FaceQueryFilterMessage_descriptor_ = file->message_type(0);
  static const int FaceQueryFilterMessage_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FaceQueryFilterMessage, face_query_filter_),
  };
  FaceQueryFilterMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      FaceQueryFilterMessage_descriptor_,
      FaceQueryFilterMessage::default_instance_,
      FaceQueryFilterMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FaceQueryFilterMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FaceQueryFilterMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(FaceQueryFilterMessage));
  FaceQueryFilterMessage_FaceQueryFilter_descriptor_ = FaceQueryFilterMessage_descriptor_->nested_type(0);
  static const int FaceQueryFilterMessage_FaceQueryFilter_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FaceQueryFilterMessage_FaceQueryFilter, face_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FaceQueryFilterMessage_FaceQueryFilter, uri_scheme_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FaceQueryFilterMessage_FaceQueryFilter, uri_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FaceQueryFilterMessage_FaceQueryFilter, local_uri_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FaceQueryFilterMessage_FaceQueryFilter, face_scope_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FaceQueryFilterMessage_FaceQueryFilter, face_persistency_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FaceQueryFilterMessage_FaceQueryFilter, link_type_),
  };
  FaceQueryFilterMessage_FaceQueryFilter_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      FaceQueryFilterMessage_FaceQueryFilter_descriptor_,
      FaceQueryFilterMessage_FaceQueryFilter::default_instance_,
      FaceQueryFilterMessage_FaceQueryFilter_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FaceQueryFilterMessage_FaceQueryFilter, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FaceQueryFilterMessage_FaceQueryFilter, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(FaceQueryFilterMessage_FaceQueryFilter));
  FaceQueryFilterMessage_FaceScope_descriptor_ = FaceQueryFilterMessage_descriptor_->enum_type(0);
  FaceQueryFilterMessage_FacePersistency_descriptor_ = FaceQueryFilterMessage_descriptor_->enum_type(1);
  FaceQueryFilterMessage_LinkType_descriptor_ = FaceQueryFilterMessage_descriptor_->enum_type(2);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_face_2dquery_2dfilter_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    FaceQueryFilterMessage_descriptor_, &FaceQueryFilterMessage::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    FaceQueryFilterMessage_FaceQueryFilter_descriptor_, &FaceQueryFilterMessage_FaceQueryFilter::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_face_2dquery_2dfilter_2eproto() {
  delete FaceQueryFilterMessage::default_instance_;
  delete FaceQueryFilterMessage_reflection_;
  delete FaceQueryFilterMessage_FaceQueryFilter::default_instance_;
  delete FaceQueryFilterMessage_FaceQueryFilter_reflection_;
}

void protobuf_AddDesc_face_2dquery_2dfilter_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\027face-query-filter.proto\022\013ndn_message\"\264"
    "\004\n\026FaceQueryFilterMessage\022O\n\021face_query_"
    "filter\030\226\001 \003(\01323.ndn_message.FaceQueryFil"
    "terMessage.FaceQueryFilter\032\256\002\n\017FaceQuery"
    "Filter\022\017\n\007face_id\030i \001(\004\022\023\n\nuri_scheme\030\203\001"
    " \001(\t\022\013\n\003uri\030r \001(\t\022\022\n\tlocal_uri\030\201\001 \001(\t\022B\n"
    "\nface_scope\030\204\001 \001(\0162-.ndn_message.FaceQue"
    "ryFilterMessage.FaceScope\022N\n\020face_persis"
    "tency\030\205\001 \001(\01623.ndn_message.FaceQueryFilt"
    "erMessage.FacePersistency\022@\n\tlink_type\030\206"
    "\001 \001(\0162,.ndn_message.FaceQueryFilterMessa"
    "ge.LinkType\"%\n\tFaceScope\022\r\n\tNON_LOCAL\020\000\022"
    "\t\n\005LOCAL\020\001\"\?\n\017FacePersistency\022\016\n\nPERSIST"
    "ENT\020\000\022\r\n\tON_DEMAND\020\001\022\r\n\tPERMANENT\020\002\"0\n\010L"
    "inkType\022\022\n\016POINT_TO_POINT\020\000\022\020\n\014MULTI_ACC"
    "ESS\020\001", 605);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "face-query-filter.proto", &protobuf_RegisterTypes);
  FaceQueryFilterMessage::default_instance_ = new FaceQueryFilterMessage();
  FaceQueryFilterMessage_FaceQueryFilter::default_instance_ = new FaceQueryFilterMessage_FaceQueryFilter();
  FaceQueryFilterMessage::default_instance_->InitAsDefaultInstance();
  FaceQueryFilterMessage_FaceQueryFilter::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_face_2dquery_2dfilter_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_face_2dquery_2dfilter_2eproto {
  StaticDescriptorInitializer_face_2dquery_2dfilter_2eproto() {
    protobuf_AddDesc_face_2dquery_2dfilter_2eproto();
  }
} static_descriptor_initializer_face_2dquery_2dfilter_2eproto_;

// ===================================================================

const ::google::protobuf::EnumDescriptor* FaceQueryFilterMessage_FaceScope_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FaceQueryFilterMessage_FaceScope_descriptor_;
}
bool FaceQueryFilterMessage_FaceScope_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const FaceQueryFilterMessage_FaceScope FaceQueryFilterMessage::NON_LOCAL;
const FaceQueryFilterMessage_FaceScope FaceQueryFilterMessage::LOCAL;
const FaceQueryFilterMessage_FaceScope FaceQueryFilterMessage::FaceScope_MIN;
const FaceQueryFilterMessage_FaceScope FaceQueryFilterMessage::FaceScope_MAX;
const int FaceQueryFilterMessage::FaceScope_ARRAYSIZE;
#endif  // _MSC_VER
const ::google::protobuf::EnumDescriptor* FaceQueryFilterMessage_FacePersistency_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FaceQueryFilterMessage_FacePersistency_descriptor_;
}
bool FaceQueryFilterMessage_FacePersistency_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const FaceQueryFilterMessage_FacePersistency FaceQueryFilterMessage::PERSISTENT;
const FaceQueryFilterMessage_FacePersistency FaceQueryFilterMessage::ON_DEMAND;
const FaceQueryFilterMessage_FacePersistency FaceQueryFilterMessage::PERMANENT;
const FaceQueryFilterMessage_FacePersistency FaceQueryFilterMessage::FacePersistency_MIN;
const FaceQueryFilterMessage_FacePersistency FaceQueryFilterMessage::FacePersistency_MAX;
const int FaceQueryFilterMessage::FacePersistency_ARRAYSIZE;
#endif  // _MSC_VER
const ::google::protobuf::EnumDescriptor* FaceQueryFilterMessage_LinkType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FaceQueryFilterMessage_LinkType_descriptor_;
}
bool FaceQueryFilterMessage_LinkType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const FaceQueryFilterMessage_LinkType FaceQueryFilterMessage::POINT_TO_POINT;
const FaceQueryFilterMessage_LinkType FaceQueryFilterMessage::MULTI_ACCESS;
const FaceQueryFilterMessage_LinkType FaceQueryFilterMessage::LinkType_MIN;
const FaceQueryFilterMessage_LinkType FaceQueryFilterMessage::LinkType_MAX;
const int FaceQueryFilterMessage::LinkType_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int FaceQueryFilterMessage_FaceQueryFilter::kFaceIdFieldNumber;
const int FaceQueryFilterMessage_FaceQueryFilter::kUriSchemeFieldNumber;
const int FaceQueryFilterMessage_FaceQueryFilter::kUriFieldNumber;
const int FaceQueryFilterMessage_FaceQueryFilter::kLocalUriFieldNumber;
const int FaceQueryFilterMessage_FaceQueryFilter::kFaceScopeFieldNumber;
const int FaceQueryFilterMessage_FaceQueryFilter::kFacePersistencyFieldNumber;
const int FaceQueryFilterMessage_FaceQueryFilter::kLinkTypeFieldNumber;
#endif  // !_MSC_VER

FaceQueryFilterMessage_FaceQueryFilter::FaceQueryFilterMessage_FaceQueryFilter()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void FaceQueryFilterMessage_FaceQueryFilter::InitAsDefaultInstance() {
}

FaceQueryFilterMessage_FaceQueryFilter::FaceQueryFilterMessage_FaceQueryFilter(const FaceQueryFilterMessage_FaceQueryFilter& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void FaceQueryFilterMessage_FaceQueryFilter::SharedCtor() {
  _cached_size_ = 0;
  face_id_ = GOOGLE_ULONGLONG(0);
  uri_scheme_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  uri_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  local_uri_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  face_scope_ = 0;
  face_persistency_ = 0;
  link_type_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

FaceQueryFilterMessage_FaceQueryFilter::~FaceQueryFilterMessage_FaceQueryFilter() {
  SharedDtor();
}

void FaceQueryFilterMessage_FaceQueryFilter::SharedDtor() {
  if (uri_scheme_ != &::google::protobuf::internal::kEmptyString) {
    delete uri_scheme_;
  }
  if (uri_ != &::google::protobuf::internal::kEmptyString) {
    delete uri_;
  }
  if (local_uri_ != &::google::protobuf::internal::kEmptyString) {
    delete local_uri_;
  }
  if (this != default_instance_) {
  }
}

void FaceQueryFilterMessage_FaceQueryFilter::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FaceQueryFilterMessage_FaceQueryFilter::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FaceQueryFilterMessage_FaceQueryFilter_descriptor_;
}

const FaceQueryFilterMessage_FaceQueryFilter& FaceQueryFilterMessage_FaceQueryFilter::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_face_2dquery_2dfilter_2eproto();
  return *default_instance_;
}

FaceQueryFilterMessage_FaceQueryFilter* FaceQueryFilterMessage_FaceQueryFilter::default_instance_ = NULL;

FaceQueryFilterMessage_FaceQueryFilter* FaceQueryFilterMessage_FaceQueryFilter::New() const {
  return new FaceQueryFilterMessage_FaceQueryFilter;
}

void FaceQueryFilterMessage_FaceQueryFilter::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    face_id_ = GOOGLE_ULONGLONG(0);
    if (has_uri_scheme()) {
      if (uri_scheme_ != &::google::protobuf::internal::kEmptyString) {
        uri_scheme_->clear();
      }
    }
    if (has_uri()) {
      if (uri_ != &::google::protobuf::internal::kEmptyString) {
        uri_->clear();
      }
    }
    if (has_local_uri()) {
      if (local_uri_ != &::google::protobuf::internal::kEmptyString) {
        local_uri_->clear();
      }
    }
    face_scope_ = 0;
    face_persistency_ = 0;
    link_type_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool FaceQueryFilterMessage_FaceQueryFilter::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint64 face_id = 105;
      case 105: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &face_id_)));
          set_has_face_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(914)) goto parse_uri;
        break;
      }

      // optional string uri = 114;
      case 114: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_uri:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_uri()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->uri().data(), this->uri().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(1034)) goto parse_local_uri;
        break;
      }

      // optional string local_uri = 129;
      case 129: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_local_uri:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_local_uri()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->local_uri().data(), this->local_uri().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(1050)) goto parse_uri_scheme;
        break;
      }

      // optional string uri_scheme = 131;
      case 131: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_uri_scheme:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_uri_scheme()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->uri_scheme().data(), this->uri_scheme().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(1056)) goto parse_face_scope;
        break;
      }

      // optional .ndn_message.FaceQueryFilterMessage.FaceScope face_scope = 132;
      case 132: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_face_scope:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::ndn_message::FaceQueryFilterMessage_FaceScope_IsValid(value)) {
            set_face_scope(static_cast< ::ndn_message::FaceQueryFilterMessage_FaceScope >(value));
          } else {
            mutable_unknown_fields()->AddVarint(132, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(1064)) goto parse_face_persistency;
        break;
      }

      // optional .ndn_message.FaceQueryFilterMessage.FacePersistency face_persistency = 133;
      case 133: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_face_persistency:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::ndn_message::FaceQueryFilterMessage_FacePersistency_IsValid(value)) {
            set_face_persistency(static_cast< ::ndn_message::FaceQueryFilterMessage_FacePersistency >(value));
          } else {
            mutable_unknown_fields()->AddVarint(133, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(1072)) goto parse_link_type;
        break;
      }

      // optional .ndn_message.FaceQueryFilterMessage.LinkType link_type = 134;
      case 134: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_link_type:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::ndn_message::FaceQueryFilterMessage_LinkType_IsValid(value)) {
            set_link_type(static_cast< ::ndn_message::FaceQueryFilterMessage_LinkType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(134, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void FaceQueryFilterMessage_FaceQueryFilter::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional uint64 face_id = 105;
  if (has_face_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(105, this->face_id(), output);
  }

  // optional string uri = 114;
  if (has_uri()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->uri().data(), this->uri().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      114, this->uri(), output);
  }

  // optional string local_uri = 129;
  if (has_local_uri()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->local_uri().data(), this->local_uri().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      129, this->local_uri(), output);
  }

  // optional string uri_scheme = 131;
  if (has_uri_scheme()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->uri_scheme().data(), this->uri_scheme().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      131, this->uri_scheme(), output);
  }

  // optional .ndn_message.FaceQueryFilterMessage.FaceScope face_scope = 132;
  if (has_face_scope()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      132, this->face_scope(), output);
  }

  // optional .ndn_message.FaceQueryFilterMessage.FacePersistency face_persistency = 133;
  if (has_face_persistency()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      133, this->face_persistency(), output);
  }

  // optional .ndn_message.FaceQueryFilterMessage.LinkType link_type = 134;
  if (has_link_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      134, this->link_type(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* FaceQueryFilterMessage_FaceQueryFilter::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional uint64 face_id = 105;
  if (has_face_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(105, this->face_id(), target);
  }

  // optional string uri = 114;
  if (has_uri()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->uri().data(), this->uri().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        114, this->uri(), target);
  }

  // optional string local_uri = 129;
  if (has_local_uri()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->local_uri().data(), this->local_uri().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        129, this->local_uri(), target);
  }

  // optional string uri_scheme = 131;
  if (has_uri_scheme()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->uri_scheme().data(), this->uri_scheme().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        131, this->uri_scheme(), target);
  }

  // optional .ndn_message.FaceQueryFilterMessage.FaceScope face_scope = 132;
  if (has_face_scope()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      132, this->face_scope(), target);
  }

  // optional .ndn_message.FaceQueryFilterMessage.FacePersistency face_persistency = 133;
  if (has_face_persistency()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      133, this->face_persistency(), target);
  }

  // optional .ndn_message.FaceQueryFilterMessage.LinkType link_type = 134;
  if (has_link_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      134, this->link_type(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int FaceQueryFilterMessage_FaceQueryFilter::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional uint64 face_id = 105;
    if (has_face_id()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->face_id());
    }

    // optional string uri_scheme = 131;
    if (has_uri_scheme()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->uri_scheme());
    }

    // optional string uri = 114;
    if (has_uri()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->uri());
    }

    // optional string local_uri = 129;
    if (has_local_uri()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->local_uri());
    }

    // optional .ndn_message.FaceQueryFilterMessage.FaceScope face_scope = 132;
    if (has_face_scope()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->face_scope());
    }

    // optional .ndn_message.FaceQueryFilterMessage.FacePersistency face_persistency = 133;
    if (has_face_persistency()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->face_persistency());
    }

    // optional .ndn_message.FaceQueryFilterMessage.LinkType link_type = 134;
    if (has_link_type()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->link_type());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FaceQueryFilterMessage_FaceQueryFilter::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const FaceQueryFilterMessage_FaceQueryFilter* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const FaceQueryFilterMessage_FaceQueryFilter*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void FaceQueryFilterMessage_FaceQueryFilter::MergeFrom(const FaceQueryFilterMessage_FaceQueryFilter& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_face_id()) {
      set_face_id(from.face_id());
    }
    if (from.has_uri_scheme()) {
      set_uri_scheme(from.uri_scheme());
    }
    if (from.has_uri()) {
      set_uri(from.uri());
    }
    if (from.has_local_uri()) {
      set_local_uri(from.local_uri());
    }
    if (from.has_face_scope()) {
      set_face_scope(from.face_scope());
    }
    if (from.has_face_persistency()) {
      set_face_persistency(from.face_persistency());
    }
    if (from.has_link_type()) {
      set_link_type(from.link_type());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void FaceQueryFilterMessage_FaceQueryFilter::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FaceQueryFilterMessage_FaceQueryFilter::CopyFrom(const FaceQueryFilterMessage_FaceQueryFilter& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FaceQueryFilterMessage_FaceQueryFilter::IsInitialized() const {

  return true;
}

void FaceQueryFilterMessage_FaceQueryFilter::Swap(FaceQueryFilterMessage_FaceQueryFilter* other) {
  if (other != this) {
    std::swap(face_id_, other->face_id_);
    std::swap(uri_scheme_, other->uri_scheme_);
    std::swap(uri_, other->uri_);
    std::swap(local_uri_, other->local_uri_);
    std::swap(face_scope_, other->face_scope_);
    std::swap(face_persistency_, other->face_persistency_);
    std::swap(link_type_, other->link_type_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata FaceQueryFilterMessage_FaceQueryFilter::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = FaceQueryFilterMessage_FaceQueryFilter_descriptor_;
  metadata.reflection = FaceQueryFilterMessage_FaceQueryFilter_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int FaceQueryFilterMessage::kFaceQueryFilterFieldNumber;
#endif  // !_MSC_VER

FaceQueryFilterMessage::FaceQueryFilterMessage()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void FaceQueryFilterMessage::InitAsDefaultInstance() {
}

FaceQueryFilterMessage::FaceQueryFilterMessage(const FaceQueryFilterMessage& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void FaceQueryFilterMessage::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

FaceQueryFilterMessage::~FaceQueryFilterMessage() {
  SharedDtor();
}

void FaceQueryFilterMessage::SharedDtor() {
  if (this != default_instance_) {
  }
}

void FaceQueryFilterMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FaceQueryFilterMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FaceQueryFilterMessage_descriptor_;
}

const FaceQueryFilterMessage& FaceQueryFilterMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_face_2dquery_2dfilter_2eproto();
  return *default_instance_;
}

FaceQueryFilterMessage* FaceQueryFilterMessage::default_instance_ = NULL;

FaceQueryFilterMessage* FaceQueryFilterMessage::New() const {
  return new FaceQueryFilterMessage;
}

void FaceQueryFilterMessage::Clear() {
  face_query_filter_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool FaceQueryFilterMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .ndn_message.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;
      case 150: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_face_query_filter:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_face_query_filter()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(1202)) goto parse_face_query_filter;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void FaceQueryFilterMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .ndn_message.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;
  for (int i = 0; i < this->face_query_filter_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      150, this->face_query_filter(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* FaceQueryFilterMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .ndn_message.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;
  for (int i = 0; i < this->face_query_filter_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        150, this->face_query_filter(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int FaceQueryFilterMessage::ByteSize() const {
  int total_size = 0;

  // repeated .ndn_message.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;
  total_size += 2 * this->face_query_filter_size();
  for (int i = 0; i < this->face_query_filter_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->face_query_filter(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FaceQueryFilterMessage::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const FaceQueryFilterMessage* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const FaceQueryFilterMessage*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void FaceQueryFilterMessage::MergeFrom(const FaceQueryFilterMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  face_query_filter_.MergeFrom(from.face_query_filter_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void FaceQueryFilterMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FaceQueryFilterMessage::CopyFrom(const FaceQueryFilterMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FaceQueryFilterMessage::IsInitialized() const {

  return true;
}

void FaceQueryFilterMessage::Swap(FaceQueryFilterMessage* other) {
  if (other != this) {
    face_query_filter_.Swap(&other->face_query_filter_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata FaceQueryFilterMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = FaceQueryFilterMessage_descriptor_;
  metadata.reflection = FaceQueryFilterMessage_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ndn_message

// @@protoc_insertion_point(global_scope)
