/*
 * Distributed under the Boost Software License, Version 1.0.
 * (See accompanying file LICENSE_1_0.txt or copy at
 * http://www.boost.org/LICENSE_1_0.txt)
 *
 * Copyright (c) 2014 Andrey Semashev
 */
/*!
 * \file   atomic/detail/caps_gcc_atomic.hpp
 *
 * This header defines feature capabilities macros
 */

#ifndef NDNBOOST_ATOMIC_DETAIL_CAPS_GCC_ATOMIC_HPP_INCLUDED_
#define NDNBOOST_ATOMIC_DETAIL_CAPS_GCC_ATOMIC_HPP_INCLUDED_

#include <ndnboost/atomic/detail/config.hpp>
#include <ndnboost/atomic/detail/int_sizes.hpp>

#ifdef NDNBOOST_HAS_PRAGMA_ONCE
#pragma once
#endif

#if defined(__i386__) && defined(__GCC_HAVE_SYNC_COMPARE_AND_SWAP_8)
#define NDNBOOST_ATOMIC_DETAIL_X86_HAS_CMPXCHG8B 1
#endif

#if defined(__x86_64__) && defined(__GCC_HAVE_SYNC_COMPARE_AND_SWAP_16)
#define NDNBOOST_ATOMIC_DETAIL_X86_HAS_CMPXCHG16B 1
#endif

#if __GCC_ATOMIC_BOOL_LOCK_FREE == 2
#define NDNBOOST_ATOMIC_FLAG_LOCK_FREE 2
#else
#define NDNBOOST_ATOMIC_FLAG_LOCK_FREE 0
#endif
#if __GCC_ATOMIC_CHAR_LOCK_FREE == 2
#define NDNBOOST_ATOMIC_CHAR_LOCK_FREE 2
#else
#define NDNBOOST_ATOMIC_CHAR_LOCK_FREE 0
#endif
#if __GCC_ATOMIC_CHAR16_T_LOCK_FREE == 2
#define NDNBOOST_ATOMIC_CHAR16_T_LOCK_FREE 2
#else
#define NDNBOOST_ATOMIC_CHAR16_T_LOCK_FREE 0
#endif
#if __GCC_ATOMIC_CHAR32_T_LOCK_FREE == 2
#define NDNBOOST_ATOMIC_CHAR32_T_LOCK_FREE 2
#else
#define NDNBOOST_ATOMIC_CHAR32_T_LOCK_FREE 0
#endif
#if __GCC_ATOMIC_WCHAR_T_LOCK_FREE == 2
#define NDNBOOST_ATOMIC_WCHAR_T_LOCK_FREE 2
#else
#define NDNBOOST_ATOMIC_WCHAR_T_LOCK_FREE 0
#endif
#if __GCC_ATOMIC_SHORT_LOCK_FREE == 2
#define NDNBOOST_ATOMIC_SHORT_LOCK_FREE 2
#else
#define NDNBOOST_ATOMIC_SHORT_LOCK_FREE 0
#endif
#if __GCC_ATOMIC_INT_LOCK_FREE == 2
#define NDNBOOST_ATOMIC_INT_LOCK_FREE 2
#else
#define NDNBOOST_ATOMIC_INT_LOCK_FREE 0
#endif
#if __GCC_ATOMIC_LONG_LOCK_FREE == 2
#define NDNBOOST_ATOMIC_LONG_LOCK_FREE 2
#else
#define NDNBOOST_ATOMIC_LONG_LOCK_FREE 0
#endif
#if __GCC_ATOMIC_LLONG_LOCK_FREE == 2
#define NDNBOOST_ATOMIC_LLONG_LOCK_FREE 2
#else
#define NDNBOOST_ATOMIC_LLONG_LOCK_FREE 0
#endif
#if defined(NDNBOOST_ATOMIC_DETAIL_X86_HAS_CMPXCHG16B) && (defined(NDNBOOST_HAS_INT128) || !defined(NDNBOOST_NO_ALIGNMENT))
#define NDNBOOST_ATOMIC_INT128_LOCK_FREE 2
#else
#define NDNBOOST_ATOMIC_INT128_LOCK_FREE 0
#endif
#if __GCC_ATOMIC_POINTER_LOCK_FREE == 2
#define NDNBOOST_ATOMIC_POINTER_LOCK_FREE 2
#else
#define NDNBOOST_ATOMIC_POINTER_LOCK_FREE 0
#endif
#if __GCC_ATOMIC_BOOL_LOCK_FREE == 2
#define NDNBOOST_ATOMIC_BOOL_LOCK_FREE 2
#else
#define NDNBOOST_ATOMIC_BOOL_LOCK_FREE 0
#endif

#define NDNBOOST_ATOMIC_INT8_LOCK_FREE NDNBOOST_ATOMIC_CHAR_LOCK_FREE

#if NDNBOOST_ATOMIC_DETAIL_SIZEOF_SHORT == 2
#define NDNBOOST_ATOMIC_INT16_LOCK_FREE NDNBOOST_ATOMIC_SHORT_LOCK_FREE
#elif NDNBOOST_ATOMIC_DETAIL_SIZEOF_INT == 2
#define NDNBOOST_ATOMIC_INT16_LOCK_FREE NDNBOOST_ATOMIC_INT_LOCK_FREE
#elif NDNBOOST_ATOMIC_DETAIL_SIZEOF_LONG == 2
#define NDNBOOST_ATOMIC_INT16_LOCK_FREE NDNBOOST_ATOMIC_LONG_LOCK_FREE
#elif NDNBOOST_ATOMIC_DETAIL_SIZEOF_LLONG == 2
#define NDNBOOST_ATOMIC_INT16_LOCK_FREE NDNBOOST_ATOMIC_LLONG_LOCK_FREE
#else
#define NDNBOOST_ATOMIC_INT16_LOCK_FREE 0
#endif

#if NDNBOOST_ATOMIC_DETAIL_SIZEOF_SHORT == 4
#define NDNBOOST_ATOMIC_INT32_LOCK_FREE NDNBOOST_ATOMIC_SHORT_LOCK_FREE
#elif NDNBOOST_ATOMIC_DETAIL_SIZEOF_INT == 4
#define NDNBOOST_ATOMIC_INT32_LOCK_FREE NDNBOOST_ATOMIC_INT_LOCK_FREE
#elif NDNBOOST_ATOMIC_DETAIL_SIZEOF_LONG == 4
#define NDNBOOST_ATOMIC_INT32_LOCK_FREE NDNBOOST_ATOMIC_LONG_LOCK_FREE
#elif NDNBOOST_ATOMIC_DETAIL_SIZEOF_LLONG == 4
#define NDNBOOST_ATOMIC_INT32_LOCK_FREE NDNBOOST_ATOMIC_LLONG_LOCK_FREE
#else
#define NDNBOOST_ATOMIC_INT32_LOCK_FREE 0
#endif

#if NDNBOOST_ATOMIC_DETAIL_SIZEOF_SHORT == 8
#define NDNBOOST_ATOMIC_INT64_LOCK_FREE NDNBOOST_ATOMIC_SHORT_LOCK_FREE
#elif NDNBOOST_ATOMIC_DETAIL_SIZEOF_INT == 8
#define NDNBOOST_ATOMIC_INT64_LOCK_FREE NDNBOOST_ATOMIC_INT_LOCK_FREE
#elif NDNBOOST_ATOMIC_DETAIL_SIZEOF_LONG == 8
#define NDNBOOST_ATOMIC_INT64_LOCK_FREE NDNBOOST_ATOMIC_LONG_LOCK_FREE
#elif NDNBOOST_ATOMIC_DETAIL_SIZEOF_LLONG == 8
#define NDNBOOST_ATOMIC_INT64_LOCK_FREE NDNBOOST_ATOMIC_LLONG_LOCK_FREE
#else
#define NDNBOOST_ATOMIC_INT64_LOCK_FREE 0
#endif

#define NDNBOOST_ATOMIC_THREAD_FENCE 2
#define NDNBOOST_ATOMIC_SIGNAL_FENCE 2

#endif // NDNBOOST_ATOMIC_DETAIL_CAPS_GCC_ATOMIC_HPP_INCLUDED_
